# Generated by Django 4.2.4 on 2023-12-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_rename_city_course_rename_country_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='materials',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
