# Generated by Django 4.2.4 on 2023-12-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_person_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='purpose',
            field=models.CharField(blank=True, choices=[('enquiry', 'Enquiry'), ('placeorder', 'Place Order'), ('return', 'Return')], max_length=20, null=True),
        ),
    ]
